#!/usr/bin/env bash
# Render the Homebrew formula for a release. Reads per-asset sha256 from a
# checksums dir (files named skill-issue-<os>-<arch>.sha256, each holding the
# bare hash) and prints Formula/skill-issue.rb to stdout.
#
# Usage: render-formula.sh <version> <checksums-dir>
set -euo pipefail

VERSION="${1:?version required, e.g. 0.2.0}"
SUMS="${2:?checksums dir required}"
BASE="https://github.com/mishanefedov/skill-issue/releases/download/v${VERSION}"

sha() { cat "$SUMS/skill-issue-$1.sha256" | awk '{print $1}'; }

cat <<EOF
# Generated by scripts/render-formula.sh on release. Do not edit by hand.
class SkillIssue < Formula
  desc "Linter that finds activation defects in AI agent skills"
  homepage "https://github.com/mishanefedov/skill-issue"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/skill-issue-darwin-arm64"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "${BASE}/skill-issue-darwin-x64"
      sha256 "$(sha darwin-x64)"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/skill-issue-linux-arm64"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "${BASE}/skill-issue-linux-x64"
      sha256 "$(sha linux-x64)"
    end
  end

  def install
    bin.install Dir["skill-issue-*"].first => "skill-issue"
  end

  test do
    assert_match "skill-issue", shell_output("#{bin}/skill-issue --help")
  end
end
EOF
